spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.game/db/game
    username: admin
    password: 123456
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      dwg: DEBUG